title:              HYERIM_Blog
email:              wkdgpfla0819@naver.com
description:        공부하고, 활동한 내용들을 정리하는 블로그 입니다.
author:             hyerim819
baseurl:            ""
url:                ""

# Social Profiles
  
github_username:   hyerim819


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
